notebooks:
  - name: example
  - name: example-2
  - name: example-large
    ingressSubdomain: "aedownstream" 
    resourceLimits:
      nvidia.com/mig-1g.10gb: 2

defaults:
  resourceLimits:
    nvidia.com/mig-1g.10gb: 1
  image: "tensorflow/tensorflow:latest-gpu-jupyter"

ingressHostname: "example.com"
