---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notebook-set
spec:
  serviceName: example-notebook
  replicas: 7
  selector:
    matchLabels:
      app: tf-notebook
  template:
    metadata:
      name: tf-notebook
      labels:
        app: tf-notebook
    spec:
      runtimeClassName: nvidia
      securityContext:
        fsGroup: 0
      containers:
      - name: tf-notebook
        image: tensorflow/tensorflow:latest-gpu-jupyter
        resources:
          limits:
            nvidia.com/mig-1g.10gb: 1
        ports:
        - containerPort: 8888
          name: notebook
  volumeClaimTemplates: []
